[project]
name = "python-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.6",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.5.3",
]
